/**
 * Famous Historic Chess Games Database
 * Contains PGN / Moves, metadata, description and opening names for historical master matches.
 */

export const FAMOUS_GAMES = [
  {
    id: 'immortal',
    title: 'Ölümsüz Oyun (The Immortal Game)',
    white: 'Adolf Anderssen',
    black: 'Lionel Kieseritzky',
    year: '1851',
    event: 'Londra',
    opening: "Kral Gambiti Kabul Edildi",
    description: "Satranç tarihinin en efsanevi romantik hücum maçı. Anderssen iki kale, fil ve vezirini feda ederek mat eder.",
    moves: [
      { from: 'e2', to: 'e4', san: 'e4' },
      { from: 'e7', to: 'e5', san: 'e5' },
      { from: 'f2', to: 'f4', san: 'f4' },
      { from: 'e5', to: 'f4', san: 'exf4' },
      { from: 'f1', to: 'c4', san: 'Bc4' },
      { from: 'd8', to: 'h4', san: 'Qh4+' },
      { from: 'e1', to: 'f1', san: 'Kf1' },
      { from: 'b7', to: 'b5', san: 'b5' },
      { from: 'c4', to: 'b5', san: 'Bxb5' },
      { from: 'g8', to: 'f6', san: 'Nf6' },
      { from: 'g1', to: 'f3', san: 'Nf3' },
      { from: 'h4', to: 'h6', san: 'Qh6' },
      { from: 'd2', to: 'd3', san: 'd3' },
      { from: 'f6', to: 'h5', san: 'Nh5' },
      { from: 'f3', to: 'h4', san: 'Nh4' },
      { from: 'h6', to: 'g5', san: 'Qg5' },
      { from: 'h4', to: 'f5', san: 'Nf5' },
      { from: 'c7', to: 'c6', san: 'c6' },
      { from: 'g2', to: 'g4', san: 'g4' },
      { from: 'h5', to: 'f6', san: 'Nf6' },
      { from: 'h1', to: 'g1', san: 'Rg1' },
      { from: 'c6', to: 'b5', san: 'cxb5' },
      { from: 'h2', to: 'h4', san: 'h4' },
      { from: 'g5', to: 'g6', san: 'Qg6' },
      { from: 'h4', to: 'h5', san: 'h5' },
      { from: 'g6', to: 'g5', san: 'Qg5' },
      { from: 'd1', to: 'f3', san: 'Qf3' },
      { from: 'f6', to: 'g8', san: 'Ng8' },
      { from: 'c1', to: 'f4', san: 'Bxf4' },
      { from: 'g5', to: 'f6', san: 'Qf6' },
      { from: 'b1', to: 'c3', san: 'Nc3' },
      { from: 'f8', to: 'c5', san: 'Bc5' },
      { from: 'c3', to: 'd5', san: 'Nd5' },
      { from: 'f6', to: 'b2', san: 'Qxb2' },
      { from: 'f4', to: 'd6', san: 'Bd6' },
      { from: 'c5', to: 'g1', san: 'Bxg1' },
      { from: 'e4', to: 'e5', san: 'e5' },
      { from: 'b2', to: 'a1', san: 'Qxa1+' },
      { from: 'f1', to: 'e2', san: 'Ke2' },
      { from: 'b8', to: 'a6', san: 'Na6' },
      { from: 'f5', to: 'g7', san: 'Nxg7+' },
      { from: 'e8', to: 'd8', san: 'Kd8' },
      { from: 'f3', to: 'f6', san: 'Qf6+' },
      { from: 'g8', to: 'f6', san: 'Nxf6' },
      { from: 'd6', to: 'e7', san: 'Be7#' }
    ]
  },
  {
    id: 'opera',
    title: 'Opera Maçı (The Opera Game)',
    white: 'Paul Morphy',
    black: 'Duke of Brunswick & Count Isouard',
    year: '1858',
    event: 'Paris Opera Binası',
    opening: "Philidor Savunması",
    description: "Hızlı gelişim ve taş koordinasyonunun ders kitabı niteliğindeki şaheseri. Morphy taşlarını feda ederek 17 hamlede mat eder.",
    moves: [
      { from: 'e2', to: 'e4', san: 'e4' },
      { from: 'e7', to: 'e5', san: 'e5' },
      { from: 'g1', to: 'f3', san: 'Nf3' },
      { from: 'd7', to: 'd6', san: 'd6' },
      { from: 'd2', to: 'd4', san: 'd4' },
      { from: 'c8', to: 'g4', san: 'Bg4' },
      { from: 'd4', to: 'e5', san: 'dxe5' },
      { from: 'g4', to: 'f3', san: 'Bxf3' },
      { from: 'd1', to: 'f3', san: 'Qxf3' },
      { from: 'd6', to: 'e5', san: 'dxe5' },
      { from: 'f1', to: 'c4', san: 'Bc4' },
      { from: 'g8', to: 'f6', san: 'Nf6' },
      { from: 'f3', to: 'b3', san: 'Qb3' },
      { from: 'd8', to: 'e7', san: 'Qe7' },
      { from: 'b1', to: 'c3', san: 'Nc3' },
      { from: 'c7', to: 'c6', san: 'c6' },
      { from: 'c1', to: 'g5', san: 'Bg5' },
      { from: 'b7', to: 'b5', san: 'b5' },
      { from: 'c3', to: 'b5', san: 'Nxb5' },
      { from: 'c6', to: 'b5', san: 'cxb5' },
      { from: 'c4', to: 'b5', san: 'Bxb5+' },
      { from: 'b8', to: 'd7', san: 'Nbd7' },
      { from: 'e1', to: 'c1', san: 'O-O-O' },
      { from: 'a8', to: 'd8', san: 'Rd8' },
      { from: 'd1', to: 'd7', san: 'Rxd7' },
      { from: 'd8', to: 'd7', san: 'Rxd7' },
      { from: 'h1', to: 'd1', san: 'Rd1' },
      { from: 'e7', to: 'e6', san: 'Qe6' },
      { from: 'g5', to: 'd7', san: 'Bxd7+' },
      { from: 'f6', to: 'd7', san: 'Nxd7' },
      { from: 'b3', to: 'b8', san: 'Qb8+' },
      { from: 'd7', to: 'b8', san: 'Nxb8' },
      { from: 'd1', to: 'd8', san: 'Rd8#' }
    ]
  },
  {
    id: 'game_of_century',
    title: 'Yüzyılın Maçı (Game of the Century)',
    white: 'Donald Byrne',
    black: 'Bobby Fischer (13 yaşında)',
    year: '1956',
    event: 'New York',
    opening: "Grünfeld Savunması",
    description: "13 yaşındaki Bobby Fischer'ın sansasyonel vezir fedasıyla tarihe geçtiği unutulmaz maç.",
    moves: [
      { from: 'g1', to: 'f3', san: 'Nf3' },
      { from: 'g8', to: 'f6', san: 'Nf6' },
      { from: 'c2', to: 'c4', san: 'c4' },
      { from: 'g7', to: 'g6', san: 'g6' },
      { from: 'b1', to: 'c3', san: 'Nc3' },
      { from: 'f8', to: 'g7', san: 'Bg7' },
      { from: 'd2', to: 'd4', san: 'd4' },
      { from: 'e8', to: 'g8', san: 'O-O' },
      { from: 'c1', to: 'f4', san: 'Bf4' },
      { from: 'd7', to: 'd5', san: 'd5' },
      { from: 'd1', to: 'b3', san: 'Qb3' },
      { from: 'd5', to: 'c4', san: 'dxc4' },
      { from: 'b3', to: 'c4', san: 'Qxc4' },
      { from: 'c7', to: 'c6', san: 'c6' },
      { from: 'e2', to: 'e4', san: 'e4' },
      { from: 'b8', to: 'd7', san: 'Nbd7' },
      { from: 'a1', to: 'd1', san: 'Rd1' },
      { from: 'd7', to: 'b6', san: 'Nb6' },
      { from: 'c4', to: 'c5', san: 'Qc5' },
      { from: 'c8', to: 'g4', san: 'Bg4' },
      { from: 'f4', to: 'g5', san: 'Bg5' },
      { from: 'b6', to: 'a4', san: 'Na4' },
      { from: 'c5', to: 'a3', san: 'Qa3' },
      { from: 'a4', to: 'c3', san: 'Nxc3' },
      { from: 'b2', to: 'c3', san: 'bxc3' },
      { from: 'f6', to: 'e4', san: 'Nxe4' },
      { from: 'g5', to: 'e7', san: 'Bxe7' },
      { from: 'd8', to: 'b6', san: 'Qb6' },
      { from: 'f1', to: 'c4', san: 'Bc4' },
      { from: 'e4', to: 'c3', san: 'Nxc3' },
      { from: 'e7', to: 'c5', san: 'Bc5' },
      { from: 'f8', to: 'e8', san: 'Rfe8+' },
      { from: 'e1', to: 'f1', san: 'Kf1' },
      { from: 'g4', to: 'e6', san: 'Be6!!' },
      { from: 'c5', to: 'b6', san: 'Bxb6' },
      { from: 'e6', to: 'c4', san: 'Bxc4+' },
      { from: 'f1', to: 'g1', san: 'Kg1' },
      { from: 'c3', to: 'e2', san: 'Ne2+' },
      { from: 'g1', to: 'f1', san: 'Kf1' },
      { from: 'e2', to: 'd4', san: 'Nxd4+' },
      { from: 'f1', to: 'g1', san: 'Kg1' },
      { from: 'd4', to: 'e2', san: 'Ne2+' },
      { from: 'g1', to: 'f1', san: 'Kf1' },
      { from: 'e2', to: 'c3', san: 'Nc3+' },
      { from: 'f1', to: 'g1', san: 'Kg1' },
      { from: 'a7', to: 'b6', san: 'axb6' },
      { from: 'a3', to: 'b4', san: 'Qb4' },
      { from: 'a8', to: 'a4', san: 'Ra4' },
      { from: 'b4', to: 'b6', san: 'Qxb6' },
      { from: 'c3', to: 'd1', san: 'Nxd1' },
      { from: 'h2', to: 'h3', san: 'h3' },
      { from: 'a4', to: 'a1', san: 'Rxa1' },
      { from: 'g1', to: 'h2', san: 'Kh2' },
      { from: 'd1', to: 'f2', san: 'Nxf2' },
      { from: 'h1', to: 'e1', san: 'Re1' },
      { from: 'e8', to: 'e1', san: 'Rxe1' },
      { from: 'b6', to: 'd8', san: 'Qd8+' },
      { from: 'g7', to: 'f8', san: 'Bf8' },
      { from: 'f3', to: 'e1', san: 'Nxe1' },
      { from: 'c4', to: 'd5', san: 'Bd5' },
      { from: 'e1', to: 'f3', san: 'Nf3' },
      { from: 'f2', to: 'e4', san: 'Ne4' },
      { from: 'd8', to: 'b8', san: 'Qb8' },
      { from: 'b7', to: 'b5', san: 'b5' },
      { from: 'h3', to: 'h4', san: 'h4' },
      { from: 'e4', to: 'e2', san: 'h5' },
      { from: 'f3', to: 'e5', san: 'Ne5' },
      { from: 'g8', to: 'g7', san: 'Kg7' },
      { from: 'g1', to: 'f1', san: 'Kg1' },
      { from: 'f8', to: 'c5', san: 'Bc5+' },
      { from: 'g1', to: 'f1', san: 'Kf1' },
      { from: 'e4', to: 'g3', san: 'Ng3+' },
      { from: 'f1', to: 'e1', san: 'Ke1' },
      { from: 'd5', to: 'b7', san: 'Bb7+' },
      { from: 'e1', to: 'd1', san: 'Kd1' },
      { from: 'c5', to: 'b6', san: 'Bb3+' },
      { from: 'd1', to: 'c1', san: 'Kc1' },
      { from: 'g3', to: 'e2', san: 'Ne2+' },
      { from: 'c1', to: 'b1', san: 'Kb1' },
      { from: 'e2', to: 'c3', san: 'Nc3+' },
      { from: 'b1', to: 'c1', san: 'Kc1' },
      { from: 'a1', to: 'c1', san: 'Rc1#' }
    ]
  },
  {
    id: 'kasparov_topalov',
    title: "Kasparov'un Başyapıtı (Kasparov's Immortal)",
    white: 'Garry Kasparov',
    black: 'Veselin Topalov',
    year: '1999',
    event: 'Wijk aan Zee',
    opening: "Pirc Savunması",
    description: "Kasparov'un kariyerinin en iyi oyunu kabul ettiği, şahı tahtanın diğer ucuna kovalayan fantastik kale fedası.",
    moves: [
      { from: 'e2', to: 'e4', san: 'e4' },
      { from: 'd7', to: 'd6', san: 'd6' },
      { from: 'd2', to: 'd4', san: 'd4' },
      { from: 'g8', to: 'f6', san: 'Nf6' },
      { from: 'b1', to: 'c3', san: 'Nc3' },
      { from: 'g7', to: 'g6', san: 'g6' },
      { from: 'c1', to: 'e3', san: 'Be3' },
      { from: 'f8', to: 'g7', san: 'Bg7' },
      { from: 'd1', to: 'd2', san: 'Qd2' },
      { from: 'c7', to: 'c6', san: 'c6' },
      { from: 'f2', to: 'f3', san: 'f3' },
      { from: 'b7', to: 'b5', san: 'b5' },
      { from: 'g1', to: 'e2', san: 'Nge2' },
      { from: 'b8', to: 'd7', san: 'Nbd7' },
      { from: 'e3', to: 'h6', san: 'Bh6' },
      { from: 'g7', to: 'h6', san: 'Bxh6' },
      { from: 'd2', to: 'h6', san: 'Qxh6' },
      { from: 'c8', to: 'b7', san: 'Bb7' },
      { from: 'a2', to: 'a3', san: 'a3' },
      { from: 'e7', to: 'e5', san: 'e5' },
      { from: 'e1', to: 'c1', san: 'O-O-O' },
      { from: 'd8', to: 'e7', san: 'Qe7' },
      { from: 'c1', to: 'b1', san: 'Kb1' },
      { from: 'a7', to: 'a6', san: 'a6' },
      { from: 'e2', to: 'c1', san: 'Nc1' },
      { from: 'e8', to: 'c8', san: 'O-O-O' },
      { from: 'c1', to: 'b3', san: 'Nb3' },
      { from: 'e5', to: 'd4', san: 'exd4' },
      { from: 'd1', to: 'd4', san: 'Rxd4' },
      { from: 'c6', to: 'c5', san: 'c5' },
      { from: 'd4', to: 'd1', san: 'Rd1' },
      { from: 'd7', to: 'b6', san: 'Nb6' },
      { from: 'g2', to: 'g3', san: 'g3' },
      { from: 'c8', to: 'b8', san: 'Kb8' },
      { from: 'b3', to: 'a5', san: 'Na5' },
      { from: 'b7', to: 'a8', san: 'Ba8' },
      { from: 'f1', to: 'h3', san: 'Bh3' },
      { from: 'd6', to: 'd5', san: 'd5' },
      { from: 'h6', to: 'f4', san: 'Qf4+' },
      { from: 'b8', to: 'a8', san: 'Ka8' },
      { from: 'h1', to: 'e1', san: 'Rhe1' },
      { from: 'd5', to: 'd4', san: 'd4' },
      { from: 'c3', to: 'd5', san: 'Nd5' },
      { from: 'b6', to: 'd5', san: 'Nbxd5' },
      { from: 'e4', to: 'd5', san: 'exd5' },
      { from: 'e7', to: 'd6', san: 'Qd6' },
      { from: 'd1', to: 'd4', san: 'Rxd4!!' },
      { from: 'c5', to: 'd4', san: 'cxd4' },
      { from: 'e1', to: 'e7', san: 'Re7+' },
      { from: 'a8', to: 'b6', san: 'Kb6' },
      { from: 'f4', to: 'd4', san: 'Qxd4+' },
      { from: 'b6', to: 'a5', san: 'Kxa5' },
      { from: 'b2', to: 'b4', san: 'b4+' },
      { from: 'a5', to: 'a4', san: 'Ka4' },
      { from: 'd4', to: 'c3', san: 'Qc3' },
      { from: 'd6', to: 'd5', san: 'Qxd5' },
      { from: 'e7', to: 'a7', san: 'Ra7' },
      { from: 'a8', to: 'b7', san: 'Bb7' },
      { from: 'a7', to: 'b7', san: 'Rxb7' },
      { from: 'd5', to: 'c4', san: 'Qc4' },
      { from: 'c3', to: 'f6', san: 'Qxf6' },
      { from: 'a4', to: 'a3', san: 'Kxa3' },
      { from: 'f6', to: 'a1', san: 'Qxa1+' },
      { from: 'a3', to: 'b4', san: 'Kb4' },
      { from: 'c2', to: 'c3', san: 'c3+' },
      { from: 'b4', to: 'c3', san: 'Kxc3' },
      { from: 'a1', to: 'a4', san: 'Qa4+' },
      { from: 'c3', to: 'd2', san: 'Kd2' },
      { from: 'a4', to: 'b3', san: 'Qb3+' },
      { from: 'd2', to: 'e2', san: 'Ke2' },
      { from: 'b3', to: 'e3', san: 'Qe3+' },
      { from: 'e2', to: 'f1', san: 'Kf1' },
      { from: 'f8', to: 'd8', san: 'Rd8' },
      { from: 'b7', to: 'd7', san: 'Rd7' }
    ]
  },
  {
    id: 'tal_portisch',
    title: 'Mikhail Tal Hücum Resitali',
    white: 'Mikhail Tal',
    black: 'Lajos Portisch',
    year: '1965',
    event: 'Adaylar Turnuvası (Bled)',
    opening: "Ruy Lopez",
    description: "Riga Sihirbazı Mikhail Tal'in feda fırtınasıyla rakip savunmayı paramparça ettiği klasik maç.",
    moves: [
      { from: 'e2', to: 'e4', san: 'e4' },
      { from: 'e7', to: 'e5', san: 'e5' },
      { from: 'g1', to: 'f3', san: 'Nf3' },
      { from: 'b8', to: 'c6', san: 'Nc6' },
      { from: 'f1', to: 'b5', san: 'Bb5' },
      { from: 'a7', to: 'a6', san: 'a6' },
      { from: 'b5', to: 'a4', san: 'Ba4' },
      { from: 'g8', to: 'f6', san: 'Nf6' },
      { from: 'e1', to: 'g1', san: 'O-O' },
      { from: 'f8', to: 'e7', san: 'Be7' },
      { from: 'f1', to: 'e1', san: 'Re1' },
      { from: 'b7', to: 'b5', san: 'b5' },
      { from: 'a4', to: 'b3', san: 'Bb3' },
      { from: 'd7', to: 'd6', san: 'd6' },
      { from: 'c2', to: 'c3', san: 'c3' },
      { from: 'e8', to: 'g8', san: 'O-O' },
      { from: 'h2', to: 'h3', san: 'h3' },
      { from: 'c8', to: 'b7', san: 'Bb7' },
      { from: 'd2', to: 'd4', san: 'd4' },
      { from: 'f8', to: 'e8', san: 'Re8' },
      { from: 'b1', to: 'd2', san: 'Nbd2' },
      { from: 'e7', to: 'f8', san: 'Bf8' },
      { from: 'a2', to: 'a4', san: 'a4' },
      { from: 'h7', to: 'h6', san: 'h6' },
      { from: 'b3', to: 'c2', san: 'Bc2' },
      { from: 'e5', to: 'd4', san: 'exd4' },
      { from: 'c3', to: 'd4', san: 'cxd4' },
      { from: 'c6', to: 'b4', san: 'Nb4' },
      { from: 'c2', to: 'b1', san: 'Bb1' },
      { from: 'c7', to: 'c5', san: 'c5' },
      { from: 'd4', to: 'd5', san: 'd5' },
      { from: 'g7', to: 'g6', san: 'g6' },
      { from: 'b2', to: 'b3', san: 'b3' },
      { from: 'f8', to: 'g7', san: 'Bg7' },
      { from: 'c1', to: 'b2', san: 'Bb2' },
      { from: 'f6', to: 'h5', san: 'Nh5' },
      { from: 'g2', to: 'g3', san: 'g3' },
      { from: 'b4', to: 'a6', san: 'Na6' },
      { from: 'b1', to: 'd3', san: 'Bd3' },
      { from: 'a6', to: 'c7', san: 'Nc7' },
      { from: 'd2', to: 'c4', san: 'Nc4' },
      { from: 'b7', to: 'c8', san: 'Bc8' },
      { from: 'g1', to: 'h2', san: 'Kh2' },
      { from: 'c8', to: 'd7', san: 'Bd7' },
      { from: 'a1', to: 'g1', san: 'Rg1' },
      { from: 'd8', to: 'f6', san: 'Qf6' },
      { from: 'd3', to: 'e2', san: 'Be2' },
      { from: 'c7', to: 'e8', san: 'Ne8' },
      { from: 'g1', to: 'g2', san: 'Rg2' },
      { from: 'g8', to: 'h8', san: 'Kh8' },
      { from: 'a1', to: 'g1', san: 'Rag1' },
      { from: 'f6', to: 'e7', san: 'Qe7' },
      { from: 'e2', to: 'd3', san: 'Bd3' },
      { from: 'e8', to: 'f6', san: 'Nf6' },
      { from: 'g3', to: 'g4', san: 'g4!' }
    ]
  }
];
